[package]
name = "dcpdoctor-wasm"
version = "0.1.1"
edition = "2021"
license = "AGPL-3.0-or-later"
description = "DCP/IMF validator — WebAssembly build for browser-based validation"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dcpdoctor-imf = { path = "../dcpdoctor-imf" }
dcpdoctor-parse = { path = "../dcpdoctor-parse" }
wasm-bindgen = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
quick-xml = "0.41"
sha1 = "0.10"
base64 = "0.22"
x509-parser = "0.16"
time = "0.3"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["console"] }

[profile.release]
opt-level = "s"
lto = true
