[package]
name = "dcpdoctor-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "DCP/IMF validation and analysis library"

[dependencies]
asdcplib = { git = "https://github.com/PostPerfection/asdcplib-rs.git", rev = "6d7b8ca" }
base64 = "0.22"
dcpdoctor-imf.workspace = true
dcpdoctor-parse.workspace = true
postkit.workspace = true
quick-xml.workspace = true
regex-lite = "0.1"
serde.workspace = true
serde_json.workspace = true
sha1.workspace = true
skrifa = "0.45"
thiserror.workspace = true
time = "0.3"
tracing.workspace = true
uuid = "1"
x509-parser = { version = "0.16", features = ["verify"] }

[dev-dependencies]
tempfile = "3"
